#------------------------------------------
# [versions] define las versiones de todas las librerías y plugins que usamos en el proyecto.
# Esto permite centralizar las versiones para que si necesitamos actualizar alguna, solo
# cambiemos aquí y automáticamente se reflejará en todas las referencias.
#------------------------------------------

[versions]
agp = "8.12.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
googleServicesversion="4.4.3"
#------------------------------------------
# Versiones específicas agregadas para Firebase
# Estas se usan para la autenticación de usuarios y la base de datos en tiempo real
#------------------------------------------
firebaseAuthV = "24.0.1"      # Versión de Firebase Authentication
firebaseDatabaseV = "22.0.0"  # Versión de Firebase Realtime Database
loginGoogleV="21.4.0"
glideV="5.0.5"                # Guarda la versión de Glide para mantener el control de versiones en un solo lugar.
ccpV="2.7.0"                  # Define la versión de la librería Country Code Picker, para que puedas referenciarla fácilmente más adelante

# Con googleServicesversion="4.4.3" defines una versión global con el nombre googleServicesversion.
# Así, si en algún momento actualizas de 4.4.3 a 4.4.4, solo cambias aquí y se actualizará en todos los lugares donde se use.
# Evita que tengas versiones duplicadas/regadas en varios archivos Gradle.

#------------------------------------------
# [libraries] define las librerías que usamos en el proyecto.
# Cada entrada indica: grupo (group), nombre (name) y versión (version.ref)
# La versión se toma de la sección [versions] usando version.ref.
#------------------------------------------
[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
#------------------------------------------
# Librerías de Firebase agregadas como parte del proyecto de registro de usuarios
#------------------------------------------
firebaseAuth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuthV" }
firebaseDatabase = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabaseV" }
loginGoogle = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "loginGoogleV" }
glide={ group = "com.github.bumptech.glide", name = "glide", version.ref = "glideV" } #Declara la librería Glide usando la versión definida arriba.
ccp = {group = "com.hbb20", name = "ccp", version.ref = "ccpV" } # Crea una referencia a la librería CCP usando el grupo, nombre y versión definida antes

#------------------------------------------
# [plugins] define los plugins de Gradle que se usarán en el proyecto
# Cada plugin tiene un id (identificador) y la versión que se tomará de [versions]
#------------------------------------------
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleService = { id = "com.google.gms.google-services", version.ref ="googleServicesversion" }

# Estás declarando un plugin de Gradle con el id: com.google.gms.google-services.
# Ese plugin es el que permite que tu app Android se conecte con Firebase Services (lee tu google-services.json y configura automáticamente las dependencias de Firebase).
# La parte version.ref = "googleServicesversion" significa que está usando la versión que definiste antes (4.4.3).